export type Service = { slug: string; title: string; summary: string; process: string; receives: string[]; importance: string[] };

export const services: Service[] = [
  { slug: "dust-fallout-air-quality", title: "Dust Fallout & Air Quality Monitoring", summary: "Measure settling dust and particulate matter to understand whether construction, material handling and industrial operations are affecting nearby environments and communities.", process: "Specially designed dust fallout buckets are installed at strategic locations and collect settling particles over a defined period, typically one month. Samples are retrieved for laboratory analysis to determine fallout rates and assess site-specific or national limits.", receives: ["Site assessment and suitable monitoring locations", "Installation and identification of monitoring units", "Routine inspection, maintenance and monthly collection", "Accredited laboratory analysis", "Interpretation and a professional monitoring report", "Exceedance identification and dust-control recommendations"], importance: ["Demonstrates compliance with environmental legislation", "Identifies emission sources and trends proactively", "Protects neighbouring communities and tests suppression measures", "Maintains audit-ready records for regulatory reporting"] },
  { slug: "asbestos-abatement-ibr", title: "Asbestos Abatement & IBR Replacement", summary: "Manage hazardous-material removal safely and compliantly while upgrading legacy infrastructure with modern asbestos-free IBR sheeting.", process: "The project begins with an asbestos inventory and local risk assessment. A regulated safe zone is established before legacy material is dismantled, sealed, transported and disposed of under mandated protocols. The cleared site receives modern IBR sheeting and a final clearance inspection.", receives: ["Comprehensive asbestos inventories and local risk assessments", "Department of Employment and Labour-compliant removal", "Secure transport and hazardous-waste disposal certificates", "Supply and professional installation of IBR sheeting", "Independent clearance certification and legal sign-off"], importance: ["Supports compliance with the 2020 Asbestos Abatement Regulations", "Reduces long-term liability and occupational-health risk", "Upgrades ageing infrastructure with weather-resistant materials", "Helps prevent enforced operational shutdowns"] },
  { slug: "water-quality-monitoring", title: "Water Quality Monitoring", summary: "Assess the physical, chemical and biological characteristics of surface water, groundwater and industrial effluent.", process: "Specialists identify strategic hydrological points such as discharge pipes, boreholes and adjacent streams. Scheduled samples are collected under sterile protocols and transported by strict chain of custody to accredited laboratories for analysis.", receives: ["A custom water-monitoring programme", "Routine surface-water, groundwater and effluent sampling", "SANAS-accredited laboratory testing", "Technical reporting against the National Water Act and municipal by-laws", "Consulting on remediation and effluent management"], importance: ["Protects operating licences and helps prevent discharge penalties", "Identifies leaks and chemical run-off early", "Protects ecosystems, groundwater and community health", "Supports Department of Water and Sanitation reporting"] },
  { slug: "occupational-health-training", title: "Specialised Occupational Health Training", summary: "Build site-specific workforce capability for high-risk environments and hazardous-material management.", process: "Certified facilitators train teams on site or in a controlled environment. Modules combine legislative frameworks with practical safety protocols; participants are assessed and competence is formally recorded.", receives: ["Asbestos Awareness and Safe Handling workshops", "Training manuals and safety documentation", "Formal assessments and Certificates of Competence", "Consolidated registers for HR and H&S audits"], importance: ["Supports employers' duty to inform and train staff", "Reduces workplace exposure, incidents and related claims", "Equips site managers and H&S officers for daily risk management"] },
  { slug: "air-emission-inventories", title: "Air Emission Inventories", summary: "Quantify pollutants from stacks, generators, boilers and fugitive sources for licensing and regulatory reporting.", process: "A site-wide source identification and characterisation exercise maps point-source and fugitive emissions. Approved emission factors, mass-balance calculations and source testing are used to compile a facility-wide inventory aligned with NAEIS reporting requirements.", receives: ["Site-wide source identification and mapping", "Pollutant-load calculations using approved methods", "An audit-ready emissions-inventory report", "NAEIS registration and annual-submission support", "Emission-reduction and abatement recommendations"], importance: ["Required for Atmospheric Emission Licence holders under NEMAQA", "Supports licence applications, renewals and audits", "Identifies major sources for targeted abatement spending", "Reduces non-reporting penalties and reputational risk"] },
  { slug: "greenhouse-gas-inventories", title: "Greenhouse Gas Emission Inventories", summary: "Quantify Scope 1, Scope 2 and, where required, Scope 3 emissions as tonnes of CO₂-equivalent.", process: "Activity data is collected across fuel combustion, process emissions, electricity consumption and fugitive sources. Approved factors under the GHG Protocol and South African National GHG Inventory methodology produce a facility- or corporate-level footprint.", receives: ["Data templates and activity-data verification", "Scope 1, 2 and applicable Scope 3 calculations", "A report aligned with the GHG Protocol and DFFE requirements", "Carbon Tax Act and NAEIS/GHG submission support", "Baseline data for emission-reduction targets"], importance: ["Supports mandatory GHG reporting and Carbon Tax Act compliance", "Provides the basis for carbon-tax liability calculations", "Supports ESG, investor and sustainability disclosure", "Identifies high-impact areas for decarbonisation investment"] },
  { slug: "tvoc-sampling-analysis", title: "TVOC Sampling and Analysis", summary: "Measure volatile organic compounds in ambient and workplace air to identify health and process risks.", process: "Calibrated equipment is deployed at indoor, workplace or perimeter locations using active or passive sampling. Accredited laboratory gas chromatography results are benchmarked against occupational-exposure limits and ambient-air guidelines.", receives: ["Site assessment and appropriate sampling locations", "Active or passive sampling with calibrated equipment", "Accredited laboratory analysis", "Reporting against exposure limits and guideline values", "Ventilation, PPE or process-control recommendations"], importance: ["Protects workers exposed to solvents, fuels and chemicals", "Supports OHS Act and Hazardous Chemical Agents compliance", "Identifies process leaks and ventilation inadequacies early", "Creates defensible occupational-hygiene records"] },
];

export const advantages = [
  { title: "The End-to-End Solution", text: "Training, monitoring, physical removal and legal sign-off are managed internally, providing one point of accountability for complex environmental projects." },
  { title: "Enterprise-Grade Capability", text: "Operational frameworks are scaled for the rigorous procurement, safety and reporting standards of parastatals and heavy logistics operators." },
  { title: "In-House Technical Authority", text: "Three specialised partners provide direct project oversight, strengthening quality control and risk mitigation." },
];
